# Copyright 2025 t54 labs
# SPDX-License-Identifier: Apache-2.0

name: CI

on:
  push:
    branches: [ main, develop, "x-402-*" ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov pytest-mock httpx

      - name: Run unit tests
        run: |
          pytest tests/test_core_flows.py tests/test_client_sdk.py -v --cov=proxy/src/x402_proxy --cov=packages/x402-secure/src/x402_client --cov-report=xml --cov-report=term || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Docker integration tests
        run: |
          ./scripts/test_docker.sh

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: |
            test-results/
            coverage.xml
